//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 18 2013 01:54:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

@class BiometricKitIdentity, NSArray, NSData, NSDictionary, NSUUID;

@protocol BiometricKitXpcProtocol
- (void)getSerialisedTemplateForIdentity:(BiometricKitIdentity *)arg1 withReplyBlock:(void (^)(NSData *))arg2;
- (void)lockSensorWithReplyBlock:(void (^)(int))arg1;
- (void)unpairSensorWithReplyBlock:(void (^)(int))arg1;
- (void)provisionSensorWithReplyBlock:(void (^)(int))arg1;
- (void)pullDebugImageData:(_Bool)arg1 withReplyBlock:(void (^)(NSData *, unsigned int, unsigned int))arg2;
- (void)pullCaptureBufferWithReplyBlock:(void (^)(NSData *))arg1;
- (void)setDebugImages:(_Bool)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)getCalibrationDataStateWithReplyBlock:(void (^)(long long))arg1;
- (void)getSensorCalibrationStatusWithReplyBlock:(void (^)(long long))arg1;
- (void)getCalBlobVersionWithReplyBlock:(void (^)(long long))arg1;
- (void)getProvisioningStateWithReplyBlock:(void (^)(long long))arg1;
- (void)preventAutonomousMatchingMode:(_Bool)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)getNodeTopologyForIdentity:(BiometricKitIdentity *)arg1 withReplyBlock:(void (^)(NSData *))arg2;
- (void)pullMatchTopologyDataWithReplyBlock:(void (^)(NSData *))arg1;
- (void)pullAlignmentDataWithReplyBlock:(void (^)(NSData *))arg1;
- (void)enrollContinueWithReplyBlock:(void (^)(int))arg1;
- (void)getMaxIdentityCount:(int)arg1 withReplyBlock:(void (^)(long long))arg2;
- (void)getCountersignedStoreTokenWithReplyBlock:(void (^)(int, NSData *))arg1;
- (void)registerStoreToken:(NSData *)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)registerDSID:(unsigned long long)arg1 withAuthToken:(NSData *)arg2 withReplyBlock:(void (^)(int))arg3;
- (void)resetEngineWithReplyBlock:(void (^)(int))arg1;
- (void)identities:(NSDictionary *)arg1 withReplyBlock:(void (^)(NSArray *))arg2;
- (void)getIdentityFromUUID:(NSUUID *)arg1 withReplyBlock:(void (^)(BiometricKitIdentity *))arg2;
- (void)removeIdentity:(BiometricKitIdentity *)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)updateIdentity:(BiometricKitIdentity *)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)cancelWithReplyBlock:(void (^)(int))arg1;
- (void)matchIdentities:(NSArray *)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)match:(NSDictionary *)arg1 withOptions:(NSDictionary *)arg2 withReplyBlock:(void (^)(int))arg3;
- (void)match:(NSDictionary *)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)enroll:(int)arg1 withAuthToken:(NSData *)arg2 withReplyBlock:(void (^)(int))arg3;
- (void)suspendWork:(_Bool)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)registerDelegate:(_Bool)arg1 withReplyBlock:(void (^)(int))arg2;
- (void)connectWithReplyBlock:(void (^)(int))arg1;
@end

