//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 18 2013 01:54:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class BiometricKitEnrollProgressCoordinates;

@interface BiometricKitEnrollProgressMergedComponent : NSObject
{
    long long _componentID;
    BiometricKitEnrollProgressCoordinates *_transformationCoordinates;
}

@property(retain, nonatomic) BiometricKitEnrollProgressCoordinates *transformationCoordinates; // @synthesize transformationCoordinates=_transformationCoordinates;
@property(nonatomic) long long componentID; // @synthesize componentID=_componentID;
- (void)dealloc;
- (id)init;

@end

