//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 18 2013 01:54:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@interface BiometricKitEnrollProgressCoordinates : NSObject
{
    double _x;
    double _y;
    double _angle;
}

@property(nonatomic) double angle; // @synthesize angle=_angle;
@property(nonatomic) double y; // @synthesize y=_y;
@property(nonatomic) double x; // @synthesize x=_x;

@end

