//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 18 2013 01:54:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface BiometricKitTemplateInfo : NSObject
{
    NSArray *_topology;
    NSDictionary *_details;
}

@property(retain, nonatomic) NSDictionary *details; // @synthesize details=_details;
@property(retain, nonatomic) NSArray *topology; // @synthesize topology=_topology;
- (void)dealloc;
- (id)init;

@end

