//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct 18 2013 01:54:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

@class BiometricKitIdentity;

@protocol BiometricKitDelegateXpcProtocol
- (void)homeButtonPressed;
- (void)statusMessage:(unsigned int)arg1;
- (void)matchResult:(BiometricKitIdentity *)arg1;
- (void)enrollResult:(BiometricKitIdentity *)arg1;
@end

